# Note: I did not know how to mount a secret during build via the
# Dockerfile. Thus, it wasn't possible to set an entrypoint with the
# isuri such that we could add arguments in the cmdline interface.
# As a workaround, I've set two distinct services in this compose file:
# rc_crawler (scrape using the leaves in leaves/leaves.json) and
# leaf_extractor (scrape for leaves and set in leaves/leaves.json).
services:
  rc_crawler:
    build:
      context: .
      dockerfile: ./Docker/rc_crawler/Dockerfile
    image: rc-crawler-image:latest
    secrets:
      # Mount the contents of the secret file
      # from the current working directory
      # to the secret volume.
      - item_server_url
    command: sh -c "python3.11 /app/prodcli-scrape -isuri $(cat /run/secrets/item_server_url) -*"

  leaf_extractor:
    build:
      context: .
      dockerfile: ./Docker/rc_crawler/Dockerfile
    image: rc-crawler-image:latest
    secrets:
      # Mount the contents of the secret file
      # from the current working directory
      # to the secret volume.
      - item_server_url
    command: sh -c "python3.11 /app/prodcli-crawl -isuri $(cat /run/secrets/item_server_url) -*"

  synchronizer:
    build:
      context: .
      dockerfile: ./Docker/synchronizer/Dockerfile
    image: synchronizer-image:latest
    secrets:
      - item_server_url
    # Synchronize today's collection in all databases
    # (grocery, joe-fresh, home-beauty-baby) with all
    # the product code data found in database.accumulate
    command: sh -c "python3.11 /app/prodcli-sync -isuri $(cat /run/secrets/item_server_url) -dbs all -dc t"

  accumulator:
    build:
      context: .
      dockerfile: ./Docker/accumulator/Dockerfile
    image: accumulator-image:latest
    secrets:
      - item_server_url
    # Accumulate all code data from 14 days ago to today
    # in each database (grocery, joe-fresh, home-beauty-baby)
    # and copy into database.accumulate
    command: sh -c "python3.11 /app/prodcli-accumulate -isuri $(cat /run/secrets/item_server_url) -dbs all -s t-14 -e t"


# Secret volumes
secrets:
  item_server_url:
    file: ./config/item_server_url.txt
