#! /opt/homebrew/bin/python3.11
# Change the path to match your python location
from ProductUploader import JSONProductUploader
import asyncio
import argparse
async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-isuri", "--item-server-uri", action="store", dest="item_server_uri", required=True, type=str)
    parser.add_argument("-d", "--debug", action="store_false", dest="debug")
    parser.add_argument("-f", "--file", action="store", dest="file")
    parser.add_argument("-db", "--database", action="store", dest="database", required=True, type=str)
    parser.add_argument("-col", "--collection", action="store", dest="collection", required=True, type=str)

    # push changes
    mxg_a = parser.add_argument_group()
    mxg_a.add_argument("--push", action="store_true", dest="push")
    mxg_a.add_argument("-qfn", "--query-filter-name", action="store", dest="query_filter_name", default=JSONProductUploader.DEFAULT_QUERY_FILTER)

    # Get products
    mxg_b = parser.add_argument_group()
    mxg_b.add_argument("--get", action="store_true", dest="get")

    # Parse args and verify that only one
    # version of the program is desired (upload XOR get products).
    args = parser.parse_args()
    item_server_uri = args.item_server_uri
    database = args.database
    collection = args.collection
    debug = args.debug
    file = args.file
    push = args.push
    query_filter_name = args.query_filter_name
    get = args.get

    push_chosen = push
    get_chosen = get

    if push_chosen and get_chosen:
        raise parser.error("Cannot simulatenously get products and push!")

    elif not push_chosen and not get_chosen:
        raise parser.error("push or get must be provided!")

    # All arguments provided are validated!
    # Start program.
    if file:
        product_interface = JSONProductUploader(item_server_uri, database, collection, debug, file)

    else:
        product_interface = JSONProductUploader(item_server_uri, database, collection, debug)

    if push_chosen:
        await product_interface.push_changes(query_filter_name)

    elif get_chosen:
        await product_interface.get_products()

asyncio.run(main())
