#! /opt/homebrew/bin/python3.11
# Change the path to match your python location
from backend.backend_interface.DBMaintainer import DBMaintainer
from backend.backend_interface.ConnectionVerifier import ConnectionVerifier
from etc.DateFormatter import InvalidDateFormatStringError
from etc.Globals import Department, Secrets
import sys
import asyncio
import argparse

async def main():
    parser = argparse.ArgumentParser(description='''
    Basic script to drop all collections defined
    in the date interval [start-date, end-date].
    ''')
    parser.add_argument("-isuri", "--item-server-uri", action="store", dest="isuri", default=Secrets.get_isuri(), type=str)
    parser.add_argument("-dbs", "--databases", action="append", nargs="+", dest="databases", required=True, type=str)
    parser.add_argument("-s", "--start-date", action="store", dest="start_date", required=True, type=str)
    parser.add_argument("-e", "--end-date", action="store", dest="end_date", required=True, type=str)
    parser.add_argument("-i", dest="interactive", action="store_true")
    args = parser.parse_args()
    db_maintainer = DBMaintainer(args.isuri, args.interactive)
    deps = args.databases[0]
    existing_deps = [dep.value for dep in Department]

    # Allow "all" to be supplied to --databases.
    # If it is, iterate through all databases.
    # Get all existing department names in the Department enum.
    if "all" in deps:
        deps = existing_deps

    # Check that every department/department is valid
    for dep in deps:
        assert isinstance(dep, str)
        if dep not in existing_deps:
            print(f"The department '{dep}' is invalid!\nPlease choose from {existing_deps}", file=sys.stderr)
            sys.exit(1)

    # Try to handle the date input for our desired
    # collection for both start and end. If an invalid date
    # representation was passed, execution will halt.
    try:
        start_date = db_maintainer.handle_date_input(args.start_date)

    except InvalidDateFormatStringError:
        print(f"The inputted date representation '{args.start_date}' is invalid!", file=sys.stderr)
        sys.exit(1)

    # Proceed similarly with the end_date
    try:
        end_date = db_maintainer.handle_date_input(args.end_date)

    except InvalidDateFormatStringError:
        print(f"The inputted date representation '{args.end_date}' is invalid!", file=sys.stderr)
        sys.exit(1)

    # Verify that the connection with the server is valid
    cv = ConnectionVerifier(args.isuri)
    await cv.verify_connection()

    # Every department is valid!
    # Now, drop every collection in
    # the established range for each dep.
    for dep in deps:
        print(f"#---- Current department: {dep} ----#")
        await db_maintainer.drop_collections(dep, start_date, end_date)
        print()
    
asyncio.run(main())
